### ISSUE TITLE
android app can not communicate with the server

### ISSUE THREAD

**Issue by wei-lee** [aerogear/apollo-voyager-ionic-example#11]
## Steps to reproduce

1. Follow the instructions to run the server, and then the android app in the emulator.
2. Getting the following UI in the android app:

![screenshot_1546445408](https://user-images.githubusercontent.com/912729/50600449-00f79c00-0ea9-11e9-89f0-f99146773c09.png)

Looks like it can not talk to the backend server.

**Comment by wei-lee** [comment]
It works fine on ios emulators.

**Comment by wtrocki** [comment]
@wei-lee Great cach! We can document that for Android emulator users will need to replace localhost with `10.0.2.2 ` to properly test this change.

**Comment by wei-lee** [comment]
@wtrocki yes, changing the ip to `10.0.2.2` worked. Where did you get that ip address from?

**Comment by wtrocki** [comment]
It looks like Android emulator is using separate network, but original machine network is still reachable: https://developer.android.com/studio/run/emulator-networking

**Comment by wtrocki** [comment]
Resolved in #13
